import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { baseConfig } from "@beyond-social/eslint-config/base";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...baseConfig,
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // All generated by Next.js and must not be hand-edited or linted.
    // `.next-dev` is the development output, kept apart from the build output
    // so the two cannot overwrite one another; see next.config.ts.
    ignores: [".next/**", ".next-dev/**", "next-env.d.ts"],
  },
];

export default config;
