import { z } from "zod";

import { ATTACHMENT_KINDS } from "@/lib/chat/attachment-kinds";

/**
 * What a turn accepts, on its own.
 *
 * Split out of `lib/chat/turn`, which is `server-only`: the composer holds a
 * turn back while it asks about a costlier model, and it stores that held turn
 * so a reload does not lose it. Reading it back is a boundary like any other
 * and is parsed rather than trusted, which needs the schema on the client.
 * Nothing here touches the database, so there is nothing to protect.
 */

const ASPECT_RATIOS = ["16:9", "9:16", "Auto"] as const;

/** The composer's ceiling: four reference photos plus one voice clip. */
const MAX_ATTACHMENTS = 5;

export const sendSchema = z.object({
  /** `new` means no project exists yet. */
  projectId: z.string().min(1),
  /**
   * Names this submission, so a retry of it is recognisable as the same one.
   *
   * Generated by the client per submit and kept across the stream attempt and
   * the server-action fallback, which is the retry that matters: the stream
   * route keeps a disconnected turn running to completion, so without this the
   * fallback runs the whole turn a second time and starts a second paid render.
   *
   * Optional in the schema and required in practice by every caller in the app.
   * A turn without one still runs, because refusing it would break any client
   * mid-deploy, and it is the one thing here worth revisiting once no such
   * client exists.
   */
  idempotencyKey: z.string().uuid().optional(),
  prompt: z.string().trim().min(1, "Describe the video first").max(2000),
  aspectRatio: z.enum(ASPECT_RATIOS).optional(),
  imageUrls: z.array(z.string().url()).max(4).optional(),
  /**
   * Footage to edit or copy motion from, as object paths in the video bucket.
   * One at a time: every model that reads video takes exactly one.
   */
  videoPaths: z.array(z.string().min(1)).max(1).optional(),
  /**
   * Object paths, not URLs. The signed URLs in `imageUrls` are what the
   * provider fetches and they expire in two hours; the path is what the thread
   * stores so it can re-sign and still render the attachment next week.
   */
  attachments: z
    .array(z.object({ kind: z.enum(ATTACHMENT_KINDS), path: z.string().min(1) }))
    .max(MAX_ATTACHMENTS)
    .optional(),
  shots: z
    .array(
      z.object({
        prompt: z.string().trim().min(1).max(500),
        duration: z.number().int().min(1).max(12),
      }),
    )
    .max(5)
    .optional(),
  /**
   * True once the caller has answered or skipped the clarifying questions.
   * Bounds the exchange to one round: without it a model that keeps finding
   * something to ask about could hold a paid action indefinitely.
   */
  clarified: z.boolean().optional(),
  /**
   * What the caller said in answer to the clarifying questions, keyed by label.
   * Folded into the brief on the server, where the prompt is built, so the
   * client never has to compose a directed prompt of its own.
   */
  clarifyAnswers: z.record(z.string().max(32), z.string().max(80)).optional(),
  /**
   * What the caller said about the costlier model they were offered, when they
   * were offered one.
   *
   * It names the model it answers about, so an answer collected for one cannot
   * approve another, and its mere presence ends the exchange: a turn carrying
   * one is never asked again, whatever it says. That is the same one-round
   * bound `clarified` gives the questions, and for the same reason.
   */
  modelAnswer: z.object({ modelId: z.string().min(1).max(120), accepted: z.boolean() }).optional(),
});
