import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { baseConfig } from "@beyond-social/eslint-config/base";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...baseConfig,
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // Both are generated by Next.js and must not be hand-edited or linted.
    ignores: [".next/**", "next-env.d.ts"],
  },
];

export default config;
